server:
  port: 8000

spring:
  application:
    name: cacheRedis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 #redis默认数据库为0号,可手动选
  cache:
    redis:
      time-to-live: 1800000   #设置缓存过期时间，可选

