server:
  port: 8000

spring:
  application:
    name: docker
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 13232@qq.com #发送邮件账号
    password: fdsa!123 #授权码
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
